name: qemu_builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install packages
        run: brew install ninja libffi gettext glib pkg-config pixman

      - name: Build QEMU
        run: ./build_macos.sh

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            dist

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install packages
        run: C:\msys64\usr\bin\bash.exe ./setup_windows.sh

      - name: Build QEMU
        run: C:\msys64\usr\bin\bash.exe ./build_windows.sh

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            dist

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install packages
        run: sudo apt install -y ninja-build libffi-dev gettext libglib2.0-dev pkg-config libpixman-1-dev

      - name: Build QEMU
        run: ./build_linux.sh

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            dist
